[project]
name = 'Decentralized-Housing-Inspection-and-Code-Enforcement-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.discrimination-prevention]
path = 'contracts/discrimination-prevention.clar'
clarity_version = 2
epoch = 2.5

[contracts.lead-remediation]
path = 'contracts/lead-remediation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
